### ISSUE TITLE
GenerativeAISwift with ObjC export

### ISSUE THREAD

**Issue by jesusdmedinac** [google/generative-ai-swift#78]
### Description of the feature request:

Adapt the package to expose objc support.

### What problem are you trying to solve with this feature?

I'm trying to create a KMP (Kotlin Multiplatform) library that adapt both Android and iOS implementations. Nevertheless, pure Swift packages are not yet supported on KMP projects.

### Any other information you'd like to share?

I would like to know if there is another way to use this amazing lib on KMP.

**Comment by paulb777** [comment]
@jesusdmedinac Thanks for the request. Like many future-looking Swift libraries, Objective-C support is not currently a priority. We're taking advantage of modern Swift features for much of the API, that don't trivially wrap to Obj-C.

If Objective-C were to be added, the approach would likely be a separate wrapper library, instead of internal `@objc` annotations.

It seems the most future-proof strategy for KMP would be pure Swift-interop instead of relying on the rapidly deprecating Objective C.

**Comment by paulb777** [comment]
This is not a currently prioritized feature request, but will continue to evaluate.

Please indicate interest with a thumbs-up vote on the issue.
