### ISSUE TITLE
Error handling for missing/wrong API key

### ISSUE THREAD

**Issue by Jerry23011** [google/generative-ai-swift#89]
### Description of the bug:

I noticed error handling for unsupportedUserLocation is improved in #85, we also encountered other error types such as API key not valid.
```swift
Printing description of error:
▿ GenerateContentError
  ▿ internalError : 1 element
    ▿ underlying : RPCError
      - httpResponseCode : 400
      - message : "API key not valid. Please pass a valid API key."
      - status : GoogleGenerativeAI.RPCStatus.invalidArgument
```

Is it possible to add this case to the package, too?

### Any other information you'd like to share?

We're thinking if it is possible to expose RPCError type in Error.swift so that we can call it directly and fetch the error message?

**Comment by tisfeng** [comment]
It is clearly shown here that there is detailed error information, so why is the return type `Error` instead of `RPCError`? Why is your `RPCError` not open to the public?

We prefer to get detailed error information and display it ourselves, instead of the vague `error.localizedDescription`.

<img width="746" alt="image" src="https://github.com/google/generative-ai-swift/assets/25194972/52bed1c5-4fbb-4513-86d0-17e2e3ae3bd5">

**Comment by andrewheard** [comment]
Thanks for your feedback, @Jerry23011 and @tisfeng! I agree that this error being buried in `GenerateContentError.internalError` is difficult to use. I think a few options we could take would be:
1. Make `RPCError` public
2. Introduce new RPC error types, such as `FailedPrecondition`, similar to the Python SDK
3. Add an `invalidAPIKey` case to `GenerateContentError`, similar to what I proposed in #85 

I personally like the last option of a specific case for common errors like this one. I think many developers are likely to run into either `invalidAPIKey` (copy/paste errors during development, revoked API keys after deployment) and/or `unsupportedUserLocation`. Making them explicit error cases might also encourage developers to handle them during development (rather than being surprised after deployment when end-users run into them).

Will discuss with my USA-based colleagues tomorrow (Martin Luther King Jr. Day there today). It's late in Europe but @peterfriese might have opinions too.

**Comment by tisfeng** [comment]
We're glad you're listening to us, and we'd like to make sure that users get clear descriptions of the errors they're getting when they request an error with Gemini, rather than vague, useless information that might otherwise come back and accuse us of having a bad experience with the app (or with Gemini).

We'd love it if you'd make sure to handle all kinds of error types, like this https://github.com/google/generative-ai-swift/pull/85, and provide clear descriptive information.

If can't, we hope you'll make the error information publicly available so that we can handle it ourselves.

**Comment by andrewheard** [comment]
Thanks, @tisfeng, we definitely appreciate you letting us know about the pain points you're running into -- I'm sure you aren't the only devs with the same questions. Since this issue is similar, I added an example in https://github.com/google/generative-ai-swift/issues/82#issuecomment-1894211125 of the pain points I ran into when trying to catch a `"User location is not supported for the API use."` error.

**Comment by tisfeng** [comment]
Thanks for the reply, I see, seems like using `String(describing: error)` for now is a workaround, although not so friendly.

Looking forward to the improvements in the later new version.

**Comment by tisfeng** [comment]
Hi, how is this issue going?

**Comment by andrewheard** [comment]
Sorry the delay, @tisfeng. I just published https://github.com/google/generative-ai-swift/releases/tag/0.4.7, which adds an [`invalidAPIKey`](https://github.com/google/generative-ai-swift/blob/dcbdb5e591e1aa2bb68851dc7515f6b0a59026cd/Sources/GoogleAI/GenerateContentError.swift#L28-L29) case to `GenerateContentError`. For example usage, please take a look at our [Chat Sample](https://github.com/google/generative-ai-swift/blob/dcbdb5e591e1aa2bb68851dc7515f6b0a59026cd/Examples/GenerativeAISample/ChatSample/Views/ErrorDetailsView.swift#L145-L158) or the [unit test](https://github.com/google/generative-ai-swift/blob/dcbdb5e591e1aa2bb68851dc7515f6b0a59026cd/Tests/GoogleAITests/GenerativeModelTests.swift#L181-L186).

Will close this issue but feel free to re-open if you find this solution doesn't meet your needs.

**Comment by Jerry23011** [comment]
Thank you @andrewheard

**Comment by elprl** [comment]
I still think this issue was closed prematurely. I'd like to access the RPCError message for the use cases that are not covered in `GenerateContentError`. For example:

[GoogleGenerativeAI] Response payload: {
  "error": {
    "code": 400,
    "message": "Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.",
    "status": "FAILED_PRECONDITION"
  }
}
